/* Write your PL/SQL query statement below */
SELECT
  TO_CHAR(W.START_DATE + 6, 'YYYY-MM-DD') AS VISITED_ON,
  SUM(C.AMOUNT)                           AS AMOUNT,
  ROUND(SUM(C.AMOUNT )/7, 2)              AS AVERAGE_AMOUNT
FROM
  (
    SELECT
      DISTINCT A.VISITED_ON AS START_DATE,
      B.VISITED_ON AS END_DATE
    FROM
      CUSTOMER A
      JOIN CUSTOMER B
      ON B.VISITED_ON - A.VISITED_ON = 6;

) W, CUSTOMER C
WHERE C.VISITED_ON BETWEEN W.START_DATE AND W.END_DATE
GROUP BY W.START_DATE
ORDER BY VISITED_ON;