/* Write your PL/SQL query statement below */
SELECT
  P.PRODUCT_NAME,
  SUM(UNIT)      AS UNIT
FROM
  PRODUCTS P
  JOIN ORDERS O
  ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
  TO_CHAR(ORDER_DATE, 'MON-YYYY') = 'FEB-2020'
GROUP BY
  P.PRODUCT_NAME
HAVING
  SUM(UNIT ) >= 100